apiVersion: v1
# change Pod to ReplicationController
kind: ReplicationController
metadata:
  name: nginx
# add this start
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx # end
    
    spec:
      containers:
      - name: nginx
        image: nginx:latest
