apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  containers:
  - image: nginx
    name: first_image
    ports:
    - containerPort: 80
  - image: curlimages/curl:7.79.1
    name: second_image
    args:
    - /bin/sh
    - -c
    - 'while true; do curl localhost:80; sleep 5; done;'